<a href="https://colab.research.google.com/github/krpadilla8/BCIS321/blob/main/KatelynPadilla_Top100Books.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/krpadilla8/BCIS321/refs/heads/main/top_100_books-2020-Katelyn_Padilla.csv')
print(df)

    Unnamed: 0  rank                           title              author  \
0          NaN     1                        Becoming      Michelle Obama
1          NaN     2            Girl, Wash Your Face       Rachel Hollis
2          NaN     3                The Wonky Donkey         Craig Smith
3          NaN     4                   Fire and Fury       Michael Wolff
4          NaN     5                            Fear        Bob Woodward
..         ...   ...                             ...                 ...
94         NaN    96               Gmorning, Gnight!  Lin-Manuel Miranda
95         NaN    97               Rich Dad Poor Dad  Robert T. Kiyosaki
96         NaN    98                   Make Your Bed  William H. McRaven
97         NaN    99  Harry Potter Paperback Box Set       J. K. Rowling
98         NaN   100  Xanathar's Guide to Everything    Wizards RPG Team

    Unnamed: 4  rating  reviews                   type  price  Unnamed: 9  \
0          NaN     4.9    13347              Hardcover  17.95         NaN
1          NaN     4.6    10521              Hardcover  13.63         NaN
2          NaN     4.7     5503              Paperback   4.99         NaN
3          NaN     4.2     9931              Hardcover  15.57         NaN
4          NaN     4.5     3220              Hardcover  15.47         NaN
..         ...     ...      ...                    ...    ...         ...
94         NaN     4.7      285              Hardcover  15.49         NaN
95         NaN     4.5     8611  Mass Market Paperback   6.45         NaN
96         NaN     4.7     2582              Hardcover  11.00         NaN
97         NaN     4.7     7742              Paperback  54.99         NaN
98         NaN     4.5      743              Hardcover  31.56         NaN

    Unnamed: 10
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
..          ...
94          NaN
95          NaN
96          NaN
97          NaN
98          NaN

[99 rows x 11 columns]

In [3]:
df.drop(["Unnamed: 0"], axis=1, inplace=True)
df.drop(["Unnamed: 4"], axis=1, inplace=True)
df.drop(["Unnamed: 9"], axis=1, inplace=True)

#df.loc[86]=[88, "Man's Search for Meaning", "Viktor E. Frankl", 4.7, 4959, "Paperback", 0]
df.loc[86,6] = 9.99
df.head()

,rank,title,author,rating,reviews,type,price,Unnamed: 10,6
0,1,Becoming,Michelle Obama,4.9,13347,Hardcover,17.95,NaN,NaN
1,2,"Girl, Wash Your Face",Rachel Hollis,4.6,10521,Hardcover,13.63,NaN,NaN
2,3,The Wonky Donkey,Craig Smith,4.7,5503,Paperback,4.99,NaN,NaN
3,4,Fire and Fury,Michael Wolff,4.2,9931,Hardcover,15.57,NaN,NaN
4,5,Fear,Bob Woodward,4.5,3220,Hardcover,15.47,NaN,NaN

In [5]:
#Paperback and Hardcover
changes = 0
i = 0
for t in df.type:
  if t == "Board Book":
    df.type.replace("Board Book", "Hardcover", inplace=True)
    changes +=1
  if t == "Mass Market Paperback":
    df.type.replace("Mass Market Paperback", "Paperback", inplace=True)
    changes +=1
  i +=1
print(changes)
df.head()

0

,rank,title,author,rating,reviews,type,price,Unnamed: 10,6
0,1,Becoming,Michelle Obama,4.9,13347,Hardcover,17.95,NaN,NaN
1,2,"Girl, Wash Your Face",Rachel Hollis,4.6,10521,Hardcover,13.63,NaN,NaN
2,3,The Wonky Donkey,Craig Smith,4.7,5503,Paperback,4.99,NaN,NaN
3,4,Fire and Fury,Michael Wolff,4.2,9931,Hardcover,15.57,NaN,NaN
4,5,Fear,Bob Woodward,4.5,3220,Hardcover,15.47,NaN,NaN

In [6]:
#Rating by Price
rating = df["rating"]
price = df["price"]
rating_by_price = rating/price
print(rating_by_price)
df.insert(4, "rating_by_price", rating_by_price)
df.sort_values(by=["rating_by_price"], ascending=False)
df.head()

0     0.272981
1     0.337491
2     0.941884
3     0.269750
4     0.290886
        ...
94    0.303422
95    0.697674
96    0.427273
97    0.085470
98    0.142586
Length: 99, dtype: float64

,rank,title,author,rating,rating_by_price,reviews,type,price,Unnamed: 10,6
0,1,Becoming,Michelle Obama,4.9,0.272981,13347,Hardcover,17.95,NaN,NaN
1,2,"Girl, Wash Your Face",Rachel Hollis,4.6,0.337491,10521,Hardcover,13.63,NaN,NaN
2,3,The Wonky Donkey,Craig Smith,4.7,0.941884,5503,Paperback,4.99,NaN,NaN
3,4,Fire and Fury,Michael Wolff,4.2,0.269750,9931,Hardcover,15.57,NaN,NaN
4,5,Fear,Bob Woodward,4.5,0.290886,3220,Hardcover,15.47,NaN,NaN

In [12]:
#Updated CSV file
df.to_csv('Katelyn_Padilla_top_100_books_cleaned.csv')